### PR TITLE
Get rid of iptables submodules

### PR DESCRIPTION
**Pull request by ranjib**
- Use distro specific iptables headers (e.g iptabled-dev in ubuntu) instead of submodules
- Use xtables.h instead of iptables.h

### CODE REVIEW

**Comment by gdm85** [comment]
@ranjib good work! thanks, I was not aware of `iptables-dev`

**Comment by gdm85** [comment]
I have removed the linking with `-lip6tc` because its functions are currently unused (as per TODO, I planned to have a separate sub-package for IPv6 functionality, although I have not verified if that's a good approach or not).

**Comment by ranjib** [comment]
awesome.
I'm trying to dynamically insert/remove rules using this library, i realized theres no go api to manipulate ipt_entry. Do you think something like that will be useful in this library?

**Comment by gdm85** [comment]
Yes, I think that was part of my plan when I started writing this (which as you may have noticed is not really complete). Be aware of this one too: https://github.com/fd0/go-iptables
However I didn't use that because my core interest was in the locking mechanism, to be able to export that functionality in this library/package (that part is already covered properly by using portions of iptables code in the C helper).

**Pull request merged**
